### ISSUE TITLE
QA_Counters_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/digital-logic-design-iiith#12]
Defect Description :
In the Feedback page of  "Counters " experiment,when we click on the feedback link, it is redirecting to an error page instead when we click on the feedback link feedback form should get downloaded

Actual Result :
In the Feedback page of  "Counters " experiment,when we click on the feedback link, it is redirecting to an error page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/digital-logic-design-iiith/blob/master/test-cases/integration_test-cases/Counters/Counters_27_Feedback_smk.org

Attachment:
![12](https://cloud.githubusercontent.com/assets/14869397/14733318/cd1d2864-087f-11e6-996c-eb8f9d2cee72.png)

**Comment by sadhanareddy** [comment]
Feedback link is fixed now. It's getting opened.

**Comment by sravanthimodepu** [comment]
Issue is fixed now. Hence closing the issue.
