### ISSUE TITLE
Enhancement Issue : Quiz result overwritable

### ISSUE THREAD

**Issue by nishant999sachdeva** [virtual-labs/digital-logic-design-iiith#166]
DESCRIPTION:
The quiz results are displayed using the input tags which are modifiable by the user. It would be much better if we use something like a <p> tag that cannot be modified by a user to display the quiz results.

SCREENSHOT 
![Screenshot from 2019-03-15 19-28-52](https://user-images.githubusercontent.com/32475507/54436481-9d1b0a80-4758-11e9-87e2-94dcb0c6a8a2.png)

I was easily able to overwrite the quiz result. That's not a healthy thing to happen to a quiz result.

**Comment by Sriharshitha27** [comment]
fixed #1060

**Comment by nishant999sachdeva** [comment]
Commit id does not work.
Run the git log command on your terminal in case you're using linux . You should be able to see the complete git id for your commit. Then update this comment with that id. At this moment, we can't  trace your commit using this partial id

**Comment by nishant999sachdeva** [comment]
17a9c193e2f660da5dc97be7d24dcb944dbd44ec

**Comment by Sriharshitha27** [comment]
17a9c193e2f660da5dc97be7d24dcb944dbd44ec

**Comment by nishant999sachdeva** [comment]
This issue belongs to the wrong lab. I am closing this issue down. The inconvenience caused is regretted.
