### ISSUE TITLE
QA_State Digrams_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/digital-logic-design-iiith#2]
Defect Description :
In the Feedback page of  "State Digrams" experiment,when we click on the feedback link, it is redirecting to an error page instead when we click on the feedback link feedback form should get downloaded

Actual Result :
In the Feedback page of  "State Digrams" experiment,when we click on the feedback link, it is redirecting to an error page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/digital-logic-design-iiith/blob/master/test-cases/integration_test-cases/State%20Digrams/State%20Digrams_27_Feedback_smk.org

Attachment:
![2](https://cloud.githubusercontent.com/assets/14869397/14733433/95fc6074-0880-11e6-9b91-7e43b227cc27.png)

**Comment by sadhanareddy** [comment]
Feedback link is fixed now. It's getting opened.

**Comment by sravanthimodepu** [comment]
Issue is fixed now. Hence closing the issue.
