### ISSUE TITLE
Decoder-with-7-segment-display_Experiment

### ISSUE THREAD

**Issue by mushie101** [virtual-labs/digital-logic-design-iiith#201]
->Defect description: The Link for pre-requisites is missing, therefore people without the pre-requisites can't download the page.

->Steps to reproduce the issue: Open the afore-mentioned page and click on the link for the simulation. If the pre-requisites are not installed the experiment wont open.

->Expected Result: There should be a link to download prerequisites.

->Actual result: only link for the experiment is available

![Screen Shot 2019-03-17 at 6 23 38 PM](https://user-images.githubusercontent.com/32613623/54491112-ce731200-48e1-11e9-84d6-27e121779cbb.png)

**Comment by mrudhvika940** [comment]
The above link is not prerequisites link. Installing Java can run this experiment.
