### ISSUE TITLE
Registers_Experiment

### ISSUE THREAD

**Issue by mushie101** [virtual-labs/digital-logic-design-iiith#205]
->Defect description: The Link for pre-requisites is missing, therefore people without the pre-requisites can't download the page.

->Steps to reproduce the issue: Open the afore-mentioned page and click on the link for the simulation. If the pre-requisites are not installed the experiment wont open.

->Expected Result: There should be a link to download prerequisites.

->Actual result: only link for the experiment is available

![Screen Shot 2019-03-17 at 6 29 16 PM](https://user-images.githubusercontent.com/32613623/54491210-97513080-48e2-11e9-8189-65dddc1cc412.png)

**Comment by MayakuntlaPULLAMMA** [comment]
#205 issue fixed 
commit-id 8d477e4

**Comment by mrudhvika940** [comment]
The above link is not prerequisites link. Installing Java can run this experiment.
