### ISSUE TITLE
QA_Latch and Flip Flops _Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/digital-logic-design-iiith#21]
Defect Description :
In "Latch and Flip Flops " experiment,there is no back to experiments link instead back to experiments link should be there in-order to view the list of experiments

Actual Result :
In "Latch and Flip Flops " experiment,the back to experiments link is not present

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/digital-logic-design-iiith/blob/master/test-cases/integration_test-cases/Latch%20and%20Flip%20Flops%20/Latch%20and%20Flip%20Flops%20_28_Back%20to%20experiment_smk.org

Attachment:
![21](https://cloud.githubusercontent.com/assets/14869397/14732924/7afa927c-087c-11e6-9950-b994dd167670.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Issue is Differed. Hence closing the issue.
