### ISSUE TITLE
QA_Latch and Flip Flops _Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/digital-logic-design-iiith#22]
Defect Description :
In the Feedback page of  "Latch and Flip Flops " experiment,when we click on the feedback link, it is redirecting to an error page instead when we click on the feedback link feedback form should get downloaded

Actual Result :
In the Feedback page of  "Latch and Flip Flops " experiment,when we click on the feedback link, it is redirecting to an error page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/digital-logic-design-iiith/blob/master/test-cases/integration_test-cases/Latch%20and%20Flip%20Flops%20/Latch%20and%20Flip%20Flops%20_27_Feedback_smk.org

Attachment:
![22](https://cloud.githubusercontent.com/assets/14869397/14732914/698991d2-087c-11e6-9adb-8de420e43013.png)

**Comment by sadhanareddy** [comment]
Feedback link is fixed now. It's getting opened.

**Comment by sravanthimodepu** [comment]
Issue is fixed now. Hence closing the issue.
