### ISSUE TITLE
QA_Comparator_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/digital-logic-design-iiith#26]
Defect Description :
In "Comparator" experiment,there is no back to experiments link instead back to experiments link should be there in-order to view the list of experiments

Actual Result :
In "Comparator" experiment,the back to experiments link is not present

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/digital-logic-design-iiith/blob/master/test-cases/integration_test-cases/Comparator/Comparator_28_Back%20to%20experiment_smk.org

Attachment:
![26](https://cloud.githubusercontent.com/assets/14869397/14732603/d63c42aa-0879-11e6-839b-bc3e68be4606.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Closing the issue.
