### ISSUE TITLE
QA_ALU with function _Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/digital-logic-design-iiith#31]
Defect Description :
In "ALU with function " experiment,there is no back to experiments link instead back to experiments link should be there in-order to view the list of experiments

Actual Result :
In "ALU with function " experiment,the back to experiments link is not present

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/digital-logic-design-iiith/blob/master/test-cases/integration_test-cases/ALU%20with%20function%20/ALU%20with%20function%20_28_Back%20to%20experiment_smk.org

Attachment:
![31](https://cloud.githubusercontent.com/assets/14869397/14732552/604904fc-0879-11e6-9bbd-acd7dff7b721.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Closing the issue.
