### ISSUE TITLE
QA_ALU with function _Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/digital-logic-design-iiith#32]
Defect Description :
In the Feedback page of  "ALU with function " experiment,when we click on the feedback link, it is redirecting to an error page instead when we click on the feedback link feedback form should get downloaded

Actual Result :
In the Feedback page of  "ALU with function " experiment,when we click on the feedback link, it is redirecting to an error page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/digital-logic-design-iiith/blob/master/test-cases/integration_test-cases/ALU%20with%20function%20/ALU%20with%20function%20_27_Feedback_smk.org

Attachment:
![32](https://cloud.githubusercontent.com/assets/14869397/14732544/515832ec-0879-11e6-8ab5-c01e0a0168b6.png)

**Comment by sadhanareddy** [comment]
Feedback link is fixed now. It's getting opened.

**Comment by sravanthimodepu** [comment]
Issue is fixed now. Hence closing the issue.
