### ISSUE TITLE
QA_Multiplexer _Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/digital-logic-design-iiith#36]
Defect Description :
In "Multiplexer " experiment,there is no back to experiments link instead back to experiments link should be there inorder to view the list of experiments

Actual Result :
In "Multiplexer " experiment,the back to experiments link is not present

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/digital-logic-design-iiith/blob/master/test-cases/integration_test-cases/Multiplexer%20/Multiplexer%20_28_Back%20to%20experiment_smk.org

Attachment:
![36](https://cloud.githubusercontent.com/assets/14869397/14732478/c8ae584a-0878-11e6-8052-5a97b941a00c.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Closing the issue.
