### ISSUE TITLE
QA_Decoder with 7-Segment Display _Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/digital-logic-design-iiith#41]
Defect Description :
In "Decoder with 7-Segment Display " experiment,there is no back to experimets link instead back to experiments link should be there inorder to view the list of experiments

Actual Result :
In "Decoder with 7-Segment Display " experiment,the back to experiments link is not present

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/digital-logic-design-iiith/blob/master/test-cases/integration_test-cases/Decoder%20with%207-Segment%20Display%20/Decoder%20with%207-Segment%20Display%20_28_Back%20to%20experiment_smk.org

Attachment:
![41](https://cloud.githubusercontent.com/assets/14869397/14732395/05d4b0d0-0878-11e6-9fff-7a74ef170b89.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Closing the issue.
