### ISSUE TITLE
QA_Decoder with 7-Segment Display _Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/digital-logic-design-iiith#42]
Defect Description :
In the Feedback page of  "Decoder with 7-Segment Display " experiment,when we click on the feedback link, it is redirecting to an error page instead when we click on the feedback link feedback form should get downloaded

Actual Result :
In the Feedback page of  "Decoder with 7-Segment Display " experiment,when we click on the feedback link, it is redirecting to an error page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/digital-logic-design-iiith/blob/master/test-cases/integration_test-cases/Decoder%20with%207-Segment%20Display%20/Decoder%20with%207-Segment%20Display%20_27_Feedback_smk.org

Attachment:
![42](https://cloud.githubusercontent.com/assets/14869397/14732387/f7e82dee-0877-11e6-84cb-5202a3fa5883.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Issue is fixed now. Hence closing the issue.
