### ISSUE TITLE
QA_Adder Circuit    _Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/digital-logic-design-iiith#46]
Defect Description :
In "Adder Circuit" experiment,there is no back to experimets link instead back to experiments link should be there inorder to view the list of experiments

Actual Result :
In "Adder Circuit" experiment,the back to experiments link is not present

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/digital-logic-design-iiith/blob/master/test-cases/integration_test-cases/Adder%20Circuit%20%20%20%20/Adder%20Circuit%20%20%20%20_28_Back%20to%20experiment_smk.org

Attachment:
![46](https://cloud.githubusercontent.com/assets/14869397/14732358/a85db082-0877-11e6-947c-666883d172cc.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Closing the issue.
