### ISSUE TITLE
QA_Adder Circuit    _Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/digital-logic-design-iiith#47]
Defect Description :
In the Feedback page of  "Adder Circuit" experiment,when we click on the feedback link, it is redirecting to an error page instead when we click on the feedback link feedback form should get downloaded

Actual Result :
In the Feedback page of  "Adder Circuit" experiment,when we click on the feedback link, it is redirecting to an error page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/digital-logic-design-iiith/blob/master/test-cases/integration_test-cases/Adder%20Circuit%20%20%20%20/Adder%20Circuit%20%20%20%20_27_Feedback_smk.org

Attachment:
![47](https://cloud.githubusercontent.com/assets/14869397/14732346/9067c972-0877-11e6-857b-e162bad14f63.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
