### ISSUE TITLE
Issues in Manual page of all the experiment

### ISSUE THREAD

**Issue by khushpreet-kaur** [virtual-labs/digital-logic-design-iiith#52]
Manual page contains the `Lab name` under `List of experiments` link in all the experiments.  It should not be there to make consistency across all the labs. 

Please see screen shot for clarification: 
![screenshot from 2016-07-26 10 09 58](https://cloud.githubusercontent.com/assets/8623775/17126782/dfa22fe6-531d-11e6-99e4-6db17869dce5.png)

**Comment by SupreethSudhakaranMenon** [comment]
As per the requirements of the issue i have removed the heading , will also attach the screenshot below.
![expt](https://user-images.githubusercontent.com/45706852/54976847-947ccc80-4fc1-11e9-86cc-f4f041491c0b.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed, hence closing.
