### ISSUE TITLE
Issue in Quiz page of all the experiments

### ISSUE THREAD

**Issue by khushpreet-kaur** [virtual-labs/digital-logic-design-iiith#53]
The text present on `Quizzes` page is bold in all the experiments.  It should have normal text instead of bold to make consistency across all the pages.

**Comment by SupreethSudhakaranMenon** [comment]
I have changed the bold text into normal text.
![boldtonormal](https://user-images.githubusercontent.com/45706852/54977168-80859a80-4fc2-11e9-91b0-344d7d4b5c9d.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed, hence closing.
