### ISSUE TITLE
 QA_DLD_brokenlink_in edx 

### ISSUE THREAD

**Issue by sadhanareddy** [virtual-labs/digital-logic-design-iiith#58]
Defect Description :
In the openedx "instructor" link which is in all the pages is giving 404 eror.

Actual Result :
link is giving 404 eror.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attatchment:
Find screenshot below.
![instructor](https://cloud.githubusercontent.com/assets/11345237/19995361/8d147faa-a27c-11e6-9053-81486d3d8159.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.
