### ISSUE TITLE
 QA_DLD_brokenlink in edx 

### ISSUE THREAD

**Issue by sadhanareddy** [virtual-labs/digital-logic-design-iiith#59]
Defect Description :
In this lab "view unit in studio" link is not working. Whereas it should redirect to the appropriate page.

Actual Result :
In this lab "view unit in studio link" is not working.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by sravanthimodepu** [comment]
Openedx is not in use now, hence closing the issue.
