### ISSUE TITLE
QA_Multipliers_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/digital-logic-design-iiith#6]
Defect Description :
In "Multipliers" experiment,there is no back to experiments link instead back to experiments link should be there in-order to view the list of experiments

Actual Result :
In "Multipliers" experiment,the back to experiments link is not present

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/digital-logic-design-iiith/blob/master/test-cases/integration_test-cases/Multipliers/Multipliers_28_Back%20to%20experiment_smk.org

Attachment:
![6](https://cloud.githubusercontent.com/assets/14869397/14733397/5fb7bfc2-0880-11e6-99c3-e89373a13fc9.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Closing the issue.

**Comment by sravanthimodepu** [comment]
Closing the issue.
