### ISSUE TITLE
QA_DigitalLogicDesign_Sections_Order_Alighment

### ISSUE THREAD

**Issue by sravanthimodepu** [virtual-labs/digital-logic-design-iiith#70]
Defect Description :
While testing this lab found, improper alignment of the sections in all the experiments.
The order of the sections should be Introduction, Theory, Objective, Manual, Procedure, Experiment, Quiz, Further Readings, Feedback..

Actual Result :
While testing this lab found, improper alignment of the sections in all the experiments.
The order of the experiment section should be after the procedure section instead of procedure after the experiment.

Environment :
OS: Windows 7, Ubuntu-14.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

**Comment by sravanthimodepu** [comment]
Arranged all the sections in proper order. Hence issue is fixed.

**Comment by rajji123** [comment]
valid issue
