### ISSUE TITLE
digital-logic-design_introduction

### ISSUE THREAD

**Issue by Rajadattu** [virtual-labs/digital-logic-design-iiith#74]
**Description:** At given address, hyperlinks for logo,home, all labs, contact, partner and computer science & engineering are not working.
**Steps to reproduce the issue:**
1)Open vlabs website through vlab.co.in
2)Select IIIT Hyderabad from participating institutes
3)Select Digital Logic Design Lab
4)Select Introduction
**Expected Result:** Corresponding pages for respective hyperlinks are expected.
**Actual Result:** A page with "The requested URL /index.html was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request." is shown.
**Screenshot:**
![digital1](https://user-images.githubusercontent.com/37900110/42338839-c5b0c01a-80a8-11e8-9734-76eb2aee2aaa.JPG)
![digital2](https://user-images.githubusercontent.com/37900110/42338851-cd0b2a4e-80a8-11e8-87e7-1e580fda54bd.JPG)

**Comment by Rajadattu** [comment]
Commit id: 0b64620

**Comment by adityagoda24** [comment]
Valid fix

**Comment by kurasaiteja** [comment]
Validated

**Comment by Sangeethashylu** [comment]
valid fix

**Comment by NAGULAVANCHA** [comment]
issue fixed
commit: 590b543

**Comment by Mani082** [comment]
Valid fix @NAGULAVANCHA

**Comment by koushik1298** [comment]
valid fix @NAGULAVANCHA

**Comment by ashfaqhaq** [comment]
valid fix @NAGULAVANCHA

**Comment by sravanthimodepu** [comment]
The issue is not fixed, need to remove **Home, All labs Partners, Contact** from the header in all the experiments of the lab.

**Comment by sravanthimodepu** [comment]
Issue is fixed for the Introduction page of the experiment, hence closing the issue.
