### ISSUE TITLE
digital-logic-design_list-of-experiments

### ISSUE THREAD

**Issue by Rajadattu** [virtual-labs/digital-logic-design-iiith#75]
**Description:** At given address, hyperlinks for logo,home, all labs, contact, partner and computer science & engineering are not working.
**Steps to reproduce the issue:**
1)Open vlabs website through vlab.co.in
2)Select IIIT Hyderabad from participating institutes
3)Select Digital Logic Design Lab
4)Select List of Experiments
**Expected Result:** Corresponding pages for respective hyperlinks are expected.
**Actual Result:** A page with "The requested URL /index.html was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request." is shown.
**Screenshot:**
![digital3](https://user-images.githubusercontent.com/37900110/42339245-127b15fc-80aa-11e8-99e8-f391b7089a6b.JPG)
![digital2](https://user-images.githubusercontent.com/37900110/42339251-16a9a9cc-80aa-11e8-9ccd-a80768abf68b.JPG)

**Comment by Rajadattu** [comment]
Commit id: https://github.com/Rajadattu/digital-logic-design-iiith/commit/7d6d44f374cf0b985d7a5cbd1b73f11817f708cc

**Comment by adityagoda24** [comment]
Valid Fix

**Comment by kurasaiteja** [comment]
Validated

**Comment by NAGULAVANCHA** [comment]
issue fixed
commit: 16d5f59

**Comment by Mani082** [comment]
Valid fix @NAGULAVANCHA

**Comment by ashfaqhaq** [comment]
valid fix @NAGULAVANCHA

**Comment by sravanthimodepu** [comment]
Issue is fixed, hence closing.
