### ISSUE TITLE
digital-logic-design_target-audience

### ISSUE THREAD

**Issue by Rajadattu** [virtual-labs/digital-logic-design-iiith#76]
**Description:** At given address, hyperlinks for logo,home, all labs, contact, partner and computer science & engineering are not working.
**Steps to reproduce the issue:**
1)Open vlabs website through vlab.co.in
2)Select IIIT Hyderabad from participating institutes
3)Select Digital Logic Design Lab
4)Select Target Audience
**Expected Result:** Corresponding pages for respective hyperlinks are expected.
**Actual Result:** A page with "The requested URL /index.html was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request." is shown.
**Screenshot:**
![digital4](https://user-images.githubusercontent.com/37900110/42339429-9be39224-80aa-11e8-97e2-1e9458553cf4.JPG)

![digital2](https://user-images.githubusercontent.com/37900110/42339251-16a9a9cc-80aa-11e8-9ccd-a80768abf68b.JPG)

**Comment by adityagoda24** [comment]
Valid fix

**Comment by NAGULAVANCHA** [comment]
issue fixed
commit: b3dbab5

**Comment by Mani082** [comment]
Valid fix @NAGULAVANCHA

**Comment by ashfaqhaq** [comment]
valid fix @NAGULAVANCHA

**Comment by sravanthimodepu** [comment]
Issue is fixed, hence closing.
